name: blenderproc
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.05.30
  - certifi=2021.5.30
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=1.1.1u
  - pip=21.2.2
  - python=3.6.13
  - readline=8.2
  - setuptools=58.0.4
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - cached-property==1.5.2
      - charset-normalizer==2.0.12
      - h5py==3.1.0
      - idna==3.4
      - kiwisolver==1.3.1
      - matplotlib==3.3.4
      - numpy==1.19.5
      - progressbar==2.5
      - pyyaml==6.0
      - requests==2.27.1
      - urllib3==1.26.16
